[package]
name = "detour-lib"
version = "0.1.0"
edition = "2021"
autotests = false
resolver = "2"


[[test]]
name = "tests"
path = "tests/progress.rs"

# [[example]]
# name = "messageboxw_detour"
# crate-type = ["cdylib"]

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[dependencies]
detour-lib-impl = { path = "impl" }
retour = "0.1.0"

[target."cfg(windows)".dependencies]
windows = {version = "0.44", features = ["Win32_System_LibraryLoader", "Win32_Foundation"]}
[target."cfg(windows)".dev-dependencies]
windows = {version = "0.44", features = ["Win32_System_LibraryLoader", "Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"]}